### ISSUE TITLE
Include Player World and ServerId. 

### ISSUE THREAD

**Issue by Athavar** [kalilistic/Dalamud.Kapture#24]
Would it be possible to include the player's world and server Id? I want to use this for a tool that receives LootEvent data over http in order to assign received loot to players.

The world and serverId should be available in the PlayerPayload of messages.

**Comment by kalilistic** [comment]
Hey, definitely possible. I won't be able to get to this right away but I'd take a PR.

The only caveat is not all the loot messages contain player payload messages. I know there's a lot of ones for the local player for example (e.g. You obtain...) - not positive if there is for any other messages. 

If that's really the only scenario with missing player payloads, could probably default to local player id/worldid in those cases. Otherwise, would need to check the gameobject (actor) table to compare the names or something.
